language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - git config --global user.email "bjhuxiaolin@corp.netease.com"
  - git config --global user.name "胡孝林"
  - hexo g -d

after_script:
  - cd ./public
  - git init
  - git config --global user.email "bjhuxiaolin@corp.netease.com"
  - git config --global user.name "胡孝林"
  - git add .
  - git commit -m "Update blog"
  - git push --force --quiet "https://${GIT_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/xiaolin8/xiaolin8.github.io.git
   
addons:
  ssh_known_hosts:
  - 192.30.253.112
  
cache:
  directories:
    - node_modules