language: node_js
node_js: stable
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy  # hexo clean && hexo g -d
after_script:
- cd ./public
- git init
- git config --global user.email "bjhuxiaolin@corp.netease.com"
- git config --global user.name "胡孝林"
- git add .
- git commit -m "Update blog"
- git push --force --quiet "https://${GIT_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - blog-source
env:
  global:
  - GH_REF: github.com/xiaolin8/xiaolin8.github.io.git
addons:
  ssh_known_hosts:
  - 192.30.253.112
  - github.com
  - xiaolin.site
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_5e0033841202_key -iv $encrypted_5e0033841202_iv
  -in id_rsa.enc -out id_rsa -d
# 改变文件权限
- chmod 600 ~/.ssh/id_rsa 
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
# 配置 git 替换为自己的信息
- git config --global user.email "bjhuxiaolin@corp.netease.com"
- git config --global user.name "胡孝林"